namespace FileStorageApi.Storage;

/// <summary>
/// Abstraction over "where file bytes physically live". Everything in the API
/// (controllers, EF Core metadata, versioning logic) talks to this interface only —
/// never to the filesystem or a specific cloud SDK directly. That means a new
/// implementation (e.g. an Azure Blob Storage or S3-backed <c>IFileStorage</c>) can be
/// dropped in and registered in <c>Program.cs</c> with no changes anywhere else.
/// </summary>
public interface IFileStorage
{
    /// <summary>
    /// Streams <paramref name="content"/> into storage under <paramref name="storageKey"/>.
    /// Implementations must not buffer the whole payload into memory — read/write in chunks.
    /// </summary>
    /// <param name="storageKey">
    /// Opaque, storage-provider-specific identifier (e.g. a relative file path for disk
    /// storage, or a blob name for cloud storage). Generated by the caller, not by the store.
    /// </param>
    /// <returns>The number of bytes written.</returns>
    Task<long> SaveAsync(string storageKey, Stream content, CancellationToken cancellationToken = default);

    /// <summary>
    /// Opens a readable, forward-only stream for the object at <paramref name="storageKey"/>.
    /// The caller is responsible for disposing the returned stream.
    /// </summary>
    Task<Stream> OpenReadAsync(string storageKey, CancellationToken cancellationToken = default);

    /// <summary>Deletes the object at <paramref name="storageKey"/> if it exists.</summary>
    Task DeleteAsync(string storageKey, CancellationToken cancellationToken = default);

    /// <summary>Checks whether an object exists at <paramref name="storageKey"/>.</summary>
    Task<bool> ExistsAsync(string storageKey, CancellationToken cancellationToken = default);
}
